### ISSUE TITLE
Add update DOI function

### ISSUE THREAD

**Issue by VivianChu** [ucsdlib/damsrepo#73]
### Descriptive summary

Add an update DOI button in the DAMS.

### Rationale

We do indeed need to update the EZID records fairly often, and this would save us a lot of time.

### Expected behavior

There will be a link to Update DOI. 

### Actual behavior

We don't have it yet.

### Related work

https://github.com/ucsdlib/damspas/issues/568

**Comment by hjsyoo** [comment]
@VivianChu One thing I wanted to ask since you're working on the minting function - there's an odd URL that gets added to the EZID record (https://ezid.cdlib.org/id/doi:10.6075/J03N21P2; see Alternative identifiers):
![image](https://user-images.githubusercontent.com/10660549/50667830-24d1e500-0f70-11e9-94ee-9a858ce7157a.png)
When I go to this URL, however, I get an error page:
![image](https://user-images.githubusercontent.com/10660549/50667863-521e9300-0f70-11e9-90c0-493c890a720c.png)
Is this field needed/useful? If not, can we remove it from the Mint DOI function?

**Comment by VivianChu** [comment]
@hjsyoo - I can remove it from the Mint DOI and update DOI function.  I see that field also exists for other old EZID record https://ezid.cdlib.org/manage/display_xml/doi:10.6075/J0D21VRF  https://ezid.cdlib.org/id/doi:10.6075/J0D21VRF .  I'm not sure if that field is needed or useful.  Let me know if you still want me to remove it.  Thanks

**Comment by hjsyoo** [comment]
@VivianChu If that field doesn't serve a purpose for you, then please remove it from both the Mint DOI and update DOI functions. Thank you!

**Comment by hjsyoo** [comment]
@arwenhutt Pinging you here, just to make sure that I'm not missing something about the Alternative identifier field that has been getting added to the EZID records?

**Comment by VivianChu** [comment]
@hjsyoo - Alternative Identifier field has been removed from Mint DOI and Update function.  For example - https://ezid.cdlib.org/id/doi:10.5072/FK26D5XN6H
Update DOI function has been added.  All of these changes have been deployed to staging.  I tried to add "Test" to the title and click the Update DOI link.  Here are some screen shots.

- Before DOI Update

![beforedoiupdate2](https://user-images.githubusercontent.com/1864660/50718099-359e5b80-1041-11e9-8c9a-5038d5abc7a5.png)


-After DOI Update

![afterdoiupdate2](https://user-images.githubusercontent.com/1864660/50718106-3df69680-1041-11e9-8157-8f631e794e6a.png)


-If there's doi, this message will be displayed.

![successfulmsg](https://user-images.githubusercontent.com/1864660/50718109-45b63b00-1041-11e9-85eb-e643406b3b9f.png)


-If no DOI is minted, this error message will be displayed.
![errordoiupdatemsg](https://user-images.githubusercontent.com/1864660/50718118-4e0e7600-1041-11e9-9cb1-0d1bb6b7dcfa.png)

Could you review the changes in staging?  Thanks

**Comment by hjsyoo** [comment]
@VivianChu This looks good to me. To clarify, we will need to push the update DOI button for every object in https://library.ucsd.edu/dc/collection/bb29737300, right? I have two thoughts here - 1) Can you change the button label to "Update DOI record" (since we're not changing the DOI itself), and 2) it occurred to me that we ought to have the geographic data added to the DOI record as well, before we push all those buttons. I'll write up a separate ticket for this. In the meantime, you're welcome to roll this out to production. I just don't think we'll use it until the geographic data can be added. Sound okay?

**Comment by VivianChu** [comment]
@hjsyoo - Sounds good.  I'll change the button label and make a request to get it deployed.  I'll keep you posted.  Thanks
